### ISSUE TITLE
Travis CI is not configured for Ruby checks because the bin/setup script fails

### ISSUE THREAD

**Issue by mturley** [RedHatCloudForms/cfme-migration_analytics#2]
The `bin/setup` script in this repo currently fails with the following error:

```
== Resetting tests ==
rails aborted!
Don't know how to build task 'app:test:vmdb:setup' (See the list of available tasks with `rake --tasks`)
/Users/mturley/.rvm/gems/ruby-2.4.2/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/mturley/.rvm/gems/ruby-2.4.2/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/mturley/.rvm/gems/ruby-2.4.2/gems/railties-5.1.7/lib/rails/command.rb:46:in `invoke'
/Users/mturley/.rvm/gems/ruby-2.4.2/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
/Users/mturley/.rvm/gems/ruby-2.4.2/gems/railties-5.1.7/lib/rails/engine/commands.rb:7:in `require'
/Users/mturley/.rvm/gems/ruby-2.4.2/gems/railties-5.1.7/lib/rails/engine/commands.rb:7:in `<top (required)>'
bin/rails:13:in `require'
bin/rails:13:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails app:test:vmdb:setup"] failed in /Users/mturley/tmp/cfme-migration_analytics ==
```

I think this is happening because I temporarily removed the `test/` directory in this commit: https://github.com/RedHatCloudForms/cfme-migration_analytics/commit/8c5c1dedb4368a2c0a15d3433d47ada9b68fcfe0 since it was overkill and I wanted to revisit a more lightweight way to test the limited amount of Ruby code in this plugin later.

Because `bin/setup` is failing, Travis was erroring out when attempting to run it for the Ruby checks I was attempting to add in https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/1. The main purpose of that PR was to configure Travis to run a check on the JavaScript, so I thought it was valuable to merge only that check and revisit the Ruby checks in a separate PR, so that #1 isn't blocking the next PR due to conflicts with the JavaScript changes I made to fix eslint errors.

The Travis CI Ruby check configurations were removed in this commit, which should be reverted after we fix `bin/setup`: https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/1/commits/3d6e7544d2b39a94c8ab52fa3808c74a7a5fab27

**Comment by mturley** [comment]
We also need to add specs for the new API endpoints, see https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/8#discussion_r311621647
